version: "3.7"

services:
  best-practices-showcase-frontend:
    image: best-practices-showcase-frontend:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
